import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {chromium} from 'playwright';
const base=process.env.DEMO_URL||'http://127.0.0.1:8767/assets/animations/ipsec-explainer/index.html';
const out=path.resolve('test-output');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1280,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>({frame:window.ipsecExplainer.player.onFrameChanged.current,duration:window.ipsecExplainer.player.onDurationChanged.current,paused:window.ipsecExplainer.player.onStateChanged.current.paused,speed:window.ipsecExplainer.player.onStateChanged.current.speed,topic:window.ipsecExplainer.topic}));
const pixels=()=>page.evaluate(()=>{const c=document.querySelector('motion-canvas-player').shadowRoot.querySelector('canvas');const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]+d[i+1]+d[i+2]>220&&d[i+3])n++;return n;});
try{
 const response=await page.goto(base+'?topic=keys');
 assert.equal(response.status(),200,'Selected keys topic must be published');
 await page.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:60000});
 assert.equal((await state()).topic,'keys');
 assert.equal((await state()).paused,true,'Initial paused / no autoplay');
 assert.ok(await pixels()>10000,'Actual Motion Canvas pixels');
 const canvasText=()=>page.evaluate(()=>{const texts=[];const walk=n=>{if(typeof n.text==='function')texts.push(n.text());n.children().forEach(walk);};walk(window.ipsecExplainer.player.playback.currentScene.getView());return texts.join('\n');});
 assert.match(await canvasText(),/A · Initiator/,'Actual scene must mount endpoint labels');
 assert.match(await canvasText(),/PSK · provisioned BEFORE/,'Actual scene must mount local credential path');
 assert.equal(await page.locator('#time').innerText(),'0초 / 36초','Display duration rounded to storyboard seconds');
 assert.ok(await page.locator('#play').isEnabled(),'Playback controls ready');
/** Keys tracer bullet: chapters, local key paths, real playback + controls. */
 assert.equal(await page.locator('[data-chapter]').count(),6,'Keys topic has six scoped chapters');
 assert.ok(Math.abs((await state()).duration-1080)<=1,'36 second storyboard at 30fps');
 await page.locator('#play').click();
 const before=(await state()).frame;
 await page.waitForFunction(f=>window.ipsecExplainer.player.onFrameChanged.current>f+15,before);
 await page.locator('#play').click();
 assert.equal((await state()).paused,true);
 const stopped=(await state()).frame;await page.waitForTimeout(300);assert.equal((await state()).frame,stopped,'Pause holds frame');
 await page.locator('[data-chapter="2"]').click();
 await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===360);
 assert.match(await page.locator('#summary').innerText(),/Z/);
 await page.locator('#speed').selectOption('1.5');assert.equal((await state()).speed,1.5);
 await page.locator('#seek').evaluate(e=>{e.value='600';e.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===600);
 await page.locator('#next').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===720);
 await page.locator('#prev').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===540);
 await page.locator('#restart').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===0);
 await page.locator('body').click({position:{x:2,y:2}});await page.keyboard.press('Space');
 await page.waitForFunction(()=>!window.ipsecExplainer.player.onStateChanged.current.paused);
 await page.keyboard.press('Space');assert.equal((await state()).paused,true);
 await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===180);
 await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===0);
 await page.locator('[data-chapter="5"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===900);
 await page.screenshot({path:path.join(out,'keys.png'),fullPage:true});
 await page.goto(base+'?topic=mitm');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal((await state()).topic,'mitm','MITM URL must select its own animation, not keys');
 assert.equal((await state()).paused,true);assert.ok(await pixels()>10000);
 assert.equal(await page.locator('[data-chapter]').count(),5);
 await page.locator('[data-chapter="1"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===180);
 assert.match(await canvasText(),/Z_AM/);assert.match(await canvasText(),/Z_MB/);assert.match(await canvasText(),/trusted = false/);
 await page.locator('[data-chapter="4"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===720);
 assert.match(await canvasText(),/ABORT/);assert.match(await canvasText(),/NO ESP DATA/);
 assert.doesNotMatch(await canvasText(),/trusted = true/);
 await page.screenshot({path:path.join(out,'mitm.png'),fullPage:true});
 await page.goto(base+'?topic=modes');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal((await state()).topic,'modes','Modes URL selects packet diagrams');assert.equal((await state()).paused,true);assert.ok(await pixels()>10000);
 assert.equal(await page.locator('[data-chapter]').count(),4);
 assert.match(await canvasText(),/hostA → hostB/);
 await page.locator('[data-chapter="1"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===180);
 assert.match(await page.locator('#summary').innerText(),/원래 IP/);
 await page.locator('#seek').evaluate(e=>{e.value='270';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===270);
 await page.screenshot({path:path.join(out,'transport.png'),fullPage:true});
 await page.locator('[data-chapter="2"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===360);
 assert.match(await canvasText(),/gwA → gwB/);assert.match(await canvasText(),/hostA → hostB/);
 await page.locator('#seek').evaluate(e=>{e.value='450';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===450);
 await page.screenshot({path:path.join(out,'tunnel.png'),fullPage:true});
 await page.locator('[data-chapter="3"]').click();await page.waitForFunction(()=>window.ipsecExplainer.player.onFrameChanged.current===540);
 assert.match(await page.locator('#summary').innerText(),/P2P/);assert.match(await canvasText(),/P2P/);
 const embed=await browser.newPage({viewport:{width:390,height:950}});
 await embed.goto('http://127.0.0.1:8767/');
 await embed.evaluate(url=>{document.body.innerHTML='';window.heights=[];const f=document.createElement('iframe');f.src=url+'?topic=keys';f.width='370';f.height='900';f.loading='lazy';f.title='IPsec';window.addEventListener('message',e=>{if(e.source===f.contentWindow&&e.origin===location.origin&&e.data.type==='ipsec-explainer-height')window.heights.push(e.data.height);});document.body.append(f);},base);
 await embed.waitForFunction(()=>window.heights.length>0,null,{timeout:15000});
 assert.ok(await embed.evaluate(()=>window.heights.every(h=>typeof h==='number'&&h>=350&&h<=2000)),'Same-origin iframe reports usable heights');
 const heightCount=await embed.evaluate(()=>window.heights.length);
 const embedded=embed.frames().find(f=>f.url().includes('ipsec-explainer/index.html'));await embedded.locator('details summary').click();
 await embed.waitForFunction(n=>window.heights.length>n,heightCount);
 assert.ok(await embed.evaluate(()=>window.heights.every(h=>h>=350&&h<=2000)),'Expanded fallback also stays within parent height contract');
 await embed.close();
 assert.deepEqual(errors,[]);
 const result={status:'passed',checks:['all topic URLs','nonempty real canvases','initial pause','playback advances','pause holds','chapter seek','slider','previous/next','restart','speed','keyboard','DH/PSK paths','two MITM secrets','AUTH abort before ESP','transport/tunnel addresses','P2P orthogonality','same-origin lazy iframe resize','expanded fallback resize'],state:await state(),pixels:await pixels(),errors};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}
