import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {chromium} from 'playwright';
const base = process.env.DEMO_URL || 'http://127.0.0.1:8765/assets/animations/ipsec/index.html';
const screenshotDir=process.env.SCREENSHOT_DIR||path.resolve('test-output');
fs.mkdirSync(screenshotDir,{recursive:true});
const browser = await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}), args:['--no-sandbox']});
const page = await browser.newPage({viewport:{width:1280,height:980}});
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
page.on('console', m=>{if(m.type()==='error') errors.push(m.text());});
try {
  const response=await page.goto(base);
  assert.equal(response.status(),200,'Demo page must be published');
  await page.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:60000});
  const state=()=>page.evaluate(()=>({frame:window.ipsecDemo.player.onFrameChanged.current,duration:window.ipsecDemo.player.onDurationChanged.current,paused:window.ipsecDemo.player.onStateChanged.current.paused,speed:window.ipsecDemo.player.onStateChanged.current.speed}));
  let s=await state();
  assert.ok(s.duration>=2100,'Entire storyboard must calculate');
  assert.equal(s.paused,true,'Do not autoplay');
  const pixels=await page.evaluate(()=>{
    const c=document.querySelector('motion-canvas-player').shadowRoot.querySelector('canvas');
    const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;
    let count=0;for(let i=0;i<d.length;i+=4)if(d[i]+d[i+1]+d[i+2]>180&&d[i+3]>0)count++;
    return count;
  });
  assert.ok(pixels>10000,'Canvas must contain real rendered diagram pixels');
  await page.screenshot({path:path.join(screenshotDir,'initial.png'),fullPage:true});
  await page.locator('#play').click();
  const before=(await state()).frame;
  await page.waitForFunction(f=>window.ipsecDemo.player.onFrameChanged.current>f+12,before);
  await page.locator('#play').click();
  assert.equal((await state()).paused,true,'Pause control must stop playback');
  await page.locator('[data-chapter="4"]').click();
  await page.waitForFunction(()=>Math.abs(window.ipsecDemo.player.onFrameChanged.current-960)<3);
  assert.match(await page.locator('#chapter-title').innerText(),/IKE_AUTH/);
  await page.screenshot({path:path.join(screenshotDir,'auth.png'),fullPage:true});
  await page.locator('#speed').selectOption('1.5');
  assert.equal((await state()).speed,1.5);
  await page.locator('[data-chapter="7"]').click();
  await page.waitForFunction(()=>Math.abs(window.ipsecDemo.player.onFrameChanged.current-1680)<3);
  const outboundDirection=await page.evaluate(()=>{
    const route=window.ipsecDemo.player.playback.currentScene.getView().children().find(n=>typeof n.points==='function');
    const points=route.points();const x=p=>Array.isArray(p)?p[0]:p.x;return x(points[1])-x(points[0]);
  });
  assert.ok(outboundDirection>0,'A to B ESP must point left-to-right, not retain the AUTH response direction');
  await page.screenshot({path:path.join(screenshotDir,'esp.png'),fullPage:true});
  await page.locator('#seek').evaluate(e=>{e.value='600';e.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>window.ipsecDemo.player.onFrameChanged.current===600);
  await page.locator('#next').click();
  await page.waitForFunction(()=>window.ipsecDemo.player.onFrameChanged.current===720);
  await page.locator('#prev').click();
  await page.waitForFunction(()=>window.ipsecDemo.player.onFrameChanged.current===480);
  await page.locator('#restart').click();
  await page.waitForFunction(()=>window.ipsecDemo.player.onFrameChanged.current===0);
  await page.setViewportSize({width:390,height:900});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile must not horizontally overflow');
  await page.screenshot({path:path.join(screenshotDir,'mobile.png'),fullPage:true});
  assert.deepEqual(errors,[],'No browser console/runtime errors');
  console.log(JSON.stringify({url:base,status:'passed',durationFrames:s.duration,renderedPixels:pixels,checks:['canvas','play','pause','chapter seek','speed','ESP direction','slider','previous/next','restart','mobile'],errors}));
} finally {await browser.close();}
